### ISSUE TITLE
flask-serial docker

### ISSUE THREAD

**Issue by simon-eller** [RedFalsh/flask-serial#6]
Hi, I'm using flask-serial in my flask project to display data from another device connected via serial on a dashboard.

Now I converted the project into a docker project and I run it with the following command:

```bash
docker-compose up --build
```

It works with a nginx server and gunicorn and the docker-compose.yaml file looks like this:
```yaml
version: '3.3'
services:
  mywebapp:
    container_name: mywebapp
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    volumes:
      - /dev:/dev
    privileged: true
    tty: true

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
    networks:
      - web_network
    depends_on: 
      - mywebapp
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
```

With this configuration somehow the uart messages from ```/dev/ttyS0``` somehow aren't forwarded to the python script. Has anyone an idea how to fix it to work?
